### PR TITLE
Fixed according to PR review of remove unnecessary abstract and create new note ui.

### LINKED ISSUE #17: Fix according to review of removed unnecessary abstract and created new note ui PR

### PR DESCRIPTION
**Pull request by anmol-kumar0815**
Fixes #17 
@yedhink _a
Please review.

### CODE REVIEW

File: app/javascript/src/components/Dashboard/Notes/Note.jsx [hunk 1]
```diff
@@ -23,8 +24,10 @@ const Note = ({ fetchNotes, note }) => {
       <div className="flex justify-between text-xl font-bold">
         <Typography style="h3">{note.title}</Typography>
         <Dropdown buttonStyle="text" icon={MenuVertical}>
-          <li>Edit</li>
-          <li onClick={handleDelete}>Delete</li>
+          <Menu>
+            <MenuItem.Button>Edit</MenuItem.Button>
+            <MenuItem.Button onClick={handleDelete}>Delete</MenuItem.Button>
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/Note.jsx:29]: Go through the Slack thread.

File: app/javascript/src/components/Dashboard/Notes/Pane/Form.jsx [hunk 2]
```diff
@@ -59,7 +55,7 @@ const NoteForm = ({ onClose, refetch, note, isEdit }) => {
               className="w-full flex-grow-0"
               label="Assigned Contact"
               name="contact"
-              options={ASSIGNED_CONTACT}
+              options={CONTACT}
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/Pane/Form.jsx:58]: This should be plural because we are assigning it to plural `options`.

**Review by yedhink — COMMENTED** [review]
@anmol-kumar0815
